version: '3.9'

services:
  mongo:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "${MONGO_EXTERNAL_PORT:-27018}:27017"
    volumes:
      - "./volumes/mongodb:/data/db"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - mimosa-net

  mongo-init:
    image: mongo:latest
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    command: >
      mongosh --host mongo:27017 --quiet --eval "
        const desiredHost = 'mongo:27017';

        try {
          const cfg = rs.conf();

          if (cfg.members[0].host !== desiredHost) {
            print('Reconfiguring replica set...');
            cfg.members[0].host = desiredHost;
            rs.reconfig(cfg, { force: true });
          } else {
            print('Replica set already correctly configured');
          }

        } catch (e) {
          print('Initialising replica set...');
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: desiredHost }]
          });
        }
      "
    networks:
      - mimosa-net

  mimosa-backend:
    build:
      context: .
      dockerfile: "./backend/Dockerfile"
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      mongo:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    environment:
      - DOMAIN=${DOMAIN}
      - BACKEND_PORT=${BACKEND_PORT}
      - PUBLIC_ORIGIN=${PUBLIC_ORIGIN:-}
      - MONGO_URI=${MONGO_URI_DOCKER}
    networks:
      - mimosa-net

  mimosa-frontend:
    build:
      context: .
      dockerfile: "./frontend/Dockerfile"
      args:
        DOMAIN: ${DOMAIN}
        BACKEND_PORT: ${BACKEND_PORT}
        BONSAI_PORT: ${BONSAI_PORT}
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - DOMAIN=${DOMAIN}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BONSAI_PORT=${BONSAI_PORT}
      - MIMOSA_RELATIVE_URL_BASE=${MIMOSA_RELATIVE_URL_BASE:-}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-}
      - NEXT_PUBLIC_BONSAI_URL=${NEXT_PUBLIC_BONSAI_URL:-}
      - PUBLIC_ORIGIN=${PUBLIC_ORIGIN:-}
    networks:
      - mimosa-net


  reportree:
    image: insapathogenomics/reportree:v2.5.4
    restart: always
    networks:
      - mimosa-net

networks:
  mimosa-net:
    driver: bridge
