#!/usr/bin/env bash

COMMAND="$1"
shift

case "$COMMAND" in
  create-user)
    npx ts-node scripts/create-user.ts "$@"
    ;;
  *)
    echo "Unknown command: $COMMAND"
    echo "Available commands:"
    echo "  mimosa create-user --p=<password> --fname=<First> --lname=<Last> --m=<email> --r=<role> --county=<HomeCounty>"
    exit 1
    ;;
esac

